name: Create PullRequest

on:
  push:
    branches: ['update/*']

env:
    DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  create-pull-request:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - uses: actions/checkout@v4

      - name: create pull request
        run: gh pr create -B ${{ env.DEFAULT_BRANCH }} -H ${{ env.BRANCH_NAME }} --title 'Merge Branch ${{ env.BRANCH_NAME }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}