name: Pull Request Auto Review

on:
  pull_request:
    branches: [ 'main' ]

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:

  check-branch:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      branch_suitable: ${{ steps.check_branch.outputs.branch_suitable }}
    steps:

      - name: check if branch is suitable for auto review
        id: check_branch
        if: contains(${{env.BRANCH_NAME}}, 'update/')
        run: echo "branch_suitable=true" >> $GITHUB_OUTPUT

  run-checks:
    needs: check-branch
    if: needs.check-branch.outputs.branch_suitable == 'true'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Run some checks
        run: sleep 15

  add-review:
    needs: run-checks
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - name: Generate API token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.PULLREQUEST_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.PULLREQUEST_GH_APP_ID }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4

      - name: approve pull request
        run: gh pr review ${{ github.event.number }} --approve -b "Approved by pull request auto review"
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}

      - name: enable auto merge
        run: gh pr merge ${{ github.event.number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}