name: Pull Request Auto Review

on:
  pull_request:
    branches: [ 'main' ]

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  setup:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - run: ls -la

  check-branch:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      branch-is-suitable: ${{ steps.check-branch.outputs.branch_suitable }}
    steps:

      - name: check if branch is suitable for auto review
        if: contains(${{env.BRANCH_NAME}}, 'update/')
        run: echo ${{env.BRANCH_NAME}}

      - name: check branch name
        run: echo ${{env.BRANCH_NAME}}

      - name: check if branch is suitable for auto review
        if: contains(${{env.BRANCH_NAME}}, 'update/')
        run: echo "branch_suitable=true" >> $GITHUB_OUTPUT

  run-checks:
    needs: check-branch
    #if: needs.check-branch.outputs.branch-is-suitable == 'true'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: test output
        env:
          IS_SUITABLE: ${{ needs.check-branch.outputs.branch_suitable}}
        run: |
          echo "isSuitable ${{ env.IS_SUITABLE }}'"

      - name: test output 2
        run: echo "isSuitable ${{ needs.check-branch.outputs.branch_suitable }}"


      - name: Run some checks
        run: sleep 15

  add-review:
    needs: run-checks-branch
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: create pull request
        run: gh pr review --comment -b "Approved by pull request auto review"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}